// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqtcgynnnghxihvykrin.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxdGNneW5ubmdoeGlodnlrcmluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg1NzMwNzIsImV4cCI6MjA4NDE0OTA3Mn0.y-r_FozYhUSdw21vxeXqT5bRPvFvZsq7avBKcQI-XDw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});